### ISSUE TITLE
Some errors occur when running the code

### ISSUE THREAD

**Issue by wangxiaobaobao** [ashudeep/Fair-PGRank#2]
Hello ashudeep,
Thank you for your implementation and I am very interested in your work. When I run the code on another dataset, it occurs that 

Traceback (most recent call last):
  File "train_amazon_dataset.py", line 608, in <module>
    args=args)
  File "train_amazon_dataset.py", line 244, in on_policy_training
    args=args)
  File "train_amazon_dataset.py", line 58, in log_and_print
    args=args)
  File "/raid/user_storage/host/Fair-PGRank/evaluation.py", line 194, in evaluate_model
    feats, rel = convert_vars_to_gpu([feats, rel], gpu_id)
  File "/raid/user_storage/host/Fair-PGRank/models.py", line 117, in convert_vars_to_gpu
    return [var.to(device) for var in varlist]
  File "/raid/user_storage/host/Fair-PGRank/models.py", line 117, in <listcomp>
    return [var.to(device) for var in varlist]
AttributeError: 'numpy.ndarray' object has no attribute 'to'

could you give me some advice to solve it?
Thank yo so much!
Best,
Xiuling

**Comment by ashudeep** [comment]
Hi Xiuling, 

Can you try without the gpu_id argument when running the code? The last version of the code that I uploaded wasn't tested on a GPU. So you can just turn off whatever command-line argument enforces a gpu_id. 

Also, I wrote the code with v1.4.0 (in 2019) so you might have to downgrade to this version (or it should still work if you just use cpu).

Thanks,
Ashudeep

**Comment by wangxiaobaobao** [comment]
OK, thank you.
